baseURL = "http://yifeili.me"
languageCode = "en-us"
title = "Yifei Li"
theme = "hugo-ivy"
googleAnalytics = ""
preserveTaxonomyNames = true
hasCJKLanguage = true


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
# [[menu.main]]
#    name = "About"
#    url = "/about/"
#    weight = 2
[[menu.main]]
    name = "Projects"
    url = "https://github.com/tudou0002"
    weight = 3
[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 4
[[menu.main]]
    name = "Tags"
   url = "/tags/"
   weight = 5

[params]
    footer = "&copy; [Yifei Li](https://localhost:1313/) 2019 | [Github](https://github.com/tudou0002)"
