baseURL = "http://example.org/"
languageCode = "en-us"
title = "Yifei Li"
theme = "hugo-ivy"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/content/about/"
    weight = 2
[[menu.main]]
    name = "Projects"
    url = "https://github.com/tudou0002"
    weight = 3
[[menu.main]]
    name = "Notes"
    url = "/content/notes/"
    weight = 4
[[menu.main]]
    name = "Blog"
    url = "/content/blog/"
    weight = 5

[params]
    footer = "&copy; [Yifei Li](https://localhost:1313/) 2019 | [Github](https://github.com/tudou0002)"
