---
title: 5 Named discrete random variables
author: Yifei Li
date: '2019-10-15'
slug: 5-named-discrete-random-variables
categories: []
tags:
  - MATH323
  - McGill
draft: no
---

# 5 Named discrete random variables

## Bernoulli 
An event has a Bernoulli r.v. if there are only two possible outcomes -- "success" ($P(X=1) = p$) and "failure" ($P(X=0) = 1-p$).

* notation: $X \sim Ber(p)$
* range of $X = \{0,1\}$
* $P(X=x) = p^x(1-p)^{1-x}$
* $E(X) = p$
* $Var(X) = p(1-p)$

## Binomial
Let X be the **number of success** in $n$ independent and identical Bernoulli trials with success probability $p$. The distribution of X is Binomial distribution with parameter n and p.

* notation: $X \sim Bin(n,p)$
* range of $X = \{0,1,2,...,n\}$
* $P(X=x) =\binom{n}{x} p^x(1-p)^{n-x}$
* $E(X) = np$
* $Var(X) = np(1-p)$


## Geometric
Let X be the **number of trials which the first success happens** in independent and identical Bernoulli trials with success probability $p$. The distribution of X is Geometric distribution with parameter p.

* notation: $X \sim Geo(p)$
* range of $X = \{0,1,2,...\}$ (infinite and countable)
* $P(X=x) =(1-p)^{x-1}p$
* $E(X) = \frac{1}{p}$
* $Var(X) = \frac{1-p}{p^2}$

## Negative Binomial
Let X be the **number of trials which the $r^{th}$ success happens** in independent and identical Bernoulli trials with success probability $p$. The distribution of X is Negative Binomial distribution with parameter p.

* notation: $X \sim NegBin(p,r)$
* range of $X = \{r,r+1,r+2,...\}$ (infinite and countable)
* $P(X=x) =\binom{x-1}{r-1}p^r(1-p)^{x-r}$
* $E(X) = \frac{r}{p}$
* $Var(X) = \frac{r(1-p)}{p^2}$

## Hypergeometric
Consider the we have a lake with $N$ fish in it, of which $r$ are tagged, $N-r$ are untagged. If a sample of $n$ fish is randomly selected, without replacement, from the lake.  Let $X$ be the number of tagged fish in the sample. Then $X$ is said to have the Hypergeometric distribution with parameters $N,r,n$.

* notation: $X \sim HGeom(N,r,n)$
* range of $X = \{0,1,2,...,min(r,n)\}$ (infinite and countable)
* $P(X=x) =\frac{\binom{r}{x}\binom{N-r}{n-x}}{\binom{N}{n}}$
* $E(X) = \frac{nr}{N}$
* $Var(X) = n\binom{r}{N}\binom{N-r}{N}\binom{N-n}{N-1}$